#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'

digit_sizes = [6, 2, 5, 5, 4, 5, 6, 3, 7, 6]

sample_input = File.read('./input').split(/\n/).map do |l|
  signal_patterns, output_value = l.split(' | ')
  signal_patterns = signal_patterns.split(' ')
  output_value = output_value.split(' ')
  {
    signal_patterns: signal_patterns,
    output_value: output_value
  }
end

out = sample_input.map do |line|
  unique_numbers = line[:output_value].filter do |c|
    c.length == digit_sizes[1] ||
      c.length == digit_sizes[4] ||
      c.length == digit_sizes[7] ||
      c.length == digit_sizes[8]
  end
  unique_numbers.count
end

pp out.inject(&:+)
