#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './diagnostic_report'

test_input = <<~TEST
  00100
  11110
  10110
  10111
  10101
  01111
  00111
  11100
  10000
  11001
  00010
  01010
TEST

report = DiagnosticReport.new(test_input.split(/\n/))

puts report.oxygen_generator_rating == 23 ? 'test passed' : "test failed: #{report.oxygen_generator_rating}"
puts report.co2_scrubber_rating == 10 ? 'test passed' : "test failed: #{report.co2_scrubber_rating}"

report = DiagnosticReport.new(File.readlines('input').map(&:chomp))

puts "Answer: #{report.oxygen_generator_rating * report.co2_scrubber_rating}"
