#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './diagnostic_report'

test_input = <<~TEST
  00100
  11110
  10110
  10111
  10101
  01111
  00111
  11100
  10000
  11001
  00010
  01010
TEST

report = DiagnosticReport.new(test_input.split(/\n/))

puts report.gamma_rate == 22 ? 'test passed' : "test failed: (#{report.gamma_rate})"
puts report.epsilon_rate == 9 ? 'test passed' : "test failed: (#{report.epsilon_rate})"
puts report.gamma_rate * report.epsilon_rate == 198 ? 'test passed' : "test failed: (#{report.gamma_rate * report.epsilon_rate})"

report = DiagnosticReport.new(File.readlines('input').map(&:chomp))

puts "Answer: #{report.gamma_rate * report.epsilon_rate}"