#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './script'
require_relative './submarine'

test_input = <<~TEST
  forward 5
  down 5
  forward 8
  up 3
  down 8
  forward 2
TEST

# Test...
commands = Script.parse(test_input)
sub = Submarine.new
sub.execute(commands)

puts sub.horizontal * sub.vertical == 150 ? 'test passed' : 'test failed'

# Exercise
commands = Script.parse(File.read('input'))
sub = Submarine.new
sub.execute(commands)

puts sub.horizontal * sub.vertical
