#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './script'
require_relative './enhanced_submarine'

test_input = <<~TEST
  forward 5
  down 5
  forward 8
  up 3
  down 8
  forward 2
TEST

# Test...
commands = Script.parse(test_input)
sub = EnhancedSubmarine.new
sub.execute(commands)

puts sub.horizontal * sub.vertical == 900 ? 'test passed' : 'test failed'

# Exercise
commands = Script.parse(File.read('input'))
sub = EnhancedSubmarine.new
sub.execute(commands)

puts sub.horizontal * sub.vertical
