#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require_relative './input'
require_relative './board'

test_input = <<~TEST
  0,9 -> 5,9
  8,0 -> 0,8
  9,4 -> 3,4
  2,2 -> 2,1
  7,0 -> 7,4
  6,4 -> 2,0
  0,9 -> 2,9
  3,4 -> 1,4
  0,0 -> 8,8
  5,5 -> 8,2
TEST


# input = Input.parse(test_input)
input = Input.parse(File.read('input'))

board = Board.new

input.each do |line| 
  line[:from].plot(line[:to]).each do |point|
    board.increment_cell(point.x, point.y)
  end
end

puts board.overlaps